# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Clone GithubPages repository and updates its submodule reference
        run: |
             git config --global user.email "autoupdater@example.com"
             git config --global user.name "Tutorials Autoupdater"
             git clone https://github.com/membraneframework/membraneframework.github.io
             cd membraneframework.github.io
             git clone https://github.com/membraneframework/membrane_tutorials  tutorials
             git add -A
             git commit -m "Update submodule"
             git push origin
             
